version: "2"
run:
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - revive
    - gocyclo
    - gosec
    - bodyclose
    - forbidigo
    - misspell
formatters:
  default: all
  enable:
    # - gci # not compatible with goimports and gofumpt, tries to change imports in different way.
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax